apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: filin9229/my-frontend-image:latest
        ports:
        - containerPort: 80
